# .github/release.yml

changelog:
  exclude:
    authors:
      - dependabot[bot]
      - pre-commit-ci[bot]
  categories:
    - title: Major Changes
      labels:
        - enhancement
    - title: Minor Changes
      labels:
        - "!bug"
        - "!enhancement"
    - title: Bugfixes
      labels:
        - bug
